rails/sdoc

- CHANGELOG.md
Hopefully it saves someone else some time!
> Review of changes in 0.4.1

- .travis.yml
> CI against Ruby 2.4

- .travis.yml
ref. [Caching Dependencies and Directories - Travis CI](https://docs.travis-ci.com/user/caching/#Bundler)
> Spcify language and bundler cache configuration for TravisCI

- lib/rdoc/discover.rb
Same as here: https://github.com/zzak/sdoc/blob/master/sdoc.gemspec#L25
> Set rdoc version same as gemspec runtime_dependency

- .gitignore
- Rakefile
- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/sdoc/class.rhtml
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
Hi,
This pull request introduces SEO tags for class files. It is split into different commits that should be self-explanatory. Action View has been introduced to simplify the generation of templates and meta tags' content.
I'm not a SEO pro though, so feel free to chime in if something can be improved.
Taking the liberty to ping @zzak & @vipulnsward.
Have a nice day ! :-)
> Add some basic SEO tags to classes

- lib/rdoc/generator/template/rails/_context.rhtml
The code what is in `context.each_section do |section, constants, attributes|` should use constants variable.
> Use constants variable

- Gemfile
> Update RDoc repository path on GitHub

- .travis.yml
- Add Ruby 2.6 on CI
- Add rubygems-update, bundler fallback to fix CI
> CI against Ruby 2.6

- README.md
It took me a while to find out how to generate sample docs for rails. Some documentation might help other contributors as well.
> Add contributing guideline for generating sample Rails doc

- CHANGELOG.md
- README.md
https://github.com/zzak/sdoc/pull/167#issuecomment-830722807
> Update readme and changelog for sdoc-merge

- lib/sdoc/version.rb
I want to make some breaking changes to the repo, please use the [stable branch](https://github.com/zzak/sdoc/tree/stable) if necessary.
> Begin sdoc 3.x development

- CHANGELOG.md
- Gemfile
- lib/rdoc/generator/template/rails/_head.rhtml
- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
- lib/sdoc/helpers.rb
Fixes #190
Blocked by rails/rails#47328 (and a release)
> Add canonical url link to all pages

- .github/workflows/test.yml
From https://github.com/zzak/sdoc/commit/59bd61611d5afcb15d38346e7f0aaf471db3411e#commitcomment-103304216
> Test on TruffleRuby

- sdoc.gemspec
> Update gem homepage

- lib/sdoc/postprocessor.rb
- spec/postprocessor_spec.rb
This uses postprocessing to version links to Rails guides.  Link URLs are changed according to `ENV["HORO_PROJECT_VERSION"]`.  For example, if `ENV["HORO_PROJECT_VERSION"]` is "3.2.1", then
```
https://guides.rubyonrails.org/testing.html
```
will be changed to
```
https://guides.rubyonrails.org/v3.2.1/testing.html
```
Or if `ENV["HORO_PROJECT_VERSION"]` is "main@1337c0d3", then the same URL will be changed to
```
https://edgeguides.rubyonrails.org/testing.html
```
> Version links to Rails guides

- lib/rdoc/generator/template/rails/index.rhtml
This file was missed in a2717d153a1151a73b4316ec2f73e9eb5f709c97.
> Use `ENV["HORO_*"]` helpers in `index.rhtml`

- spec/rdoc_generator_spec.rb
In addition to simplifying individual tests, the `parse_options` helper more accurately reflects end-to-end options parsing behavior.
> Add `parse_options` helper to `rdoc_generator_spec.rb`

- Gemfile
> Add puma to Gemfile

- lib/rdoc/generator/template/rails/resources/css/main.css
| --- | --- |
| ![before1](https://github.com/rails/sdoc/assets/771968/c63321f2-6949-4605-8056-de7ce847351a) | ![after1](https://github.com/rails/sdoc/assets/771968/701d97ea-98f8-469b-8729-47ee367eef68) |
| ![before2](https://github.com/rails/sdoc/assets/771968/5db2365f-74af-4a1b-b8e4-d55fd7af5759) | ![after2](https://github.com/rails/sdoc/assets/771968/363c5655-20c2-4cdd-9b17-a07b69a8f413) |
> Style `blockquote` elements

- CHANGELOG.md
- spec/postprocessor_spec.rb
Follow-up to 87683a14e85b0d5cc311aa8e65dd6d2765fe02ef.
This adds a CHANGELOG entry, plus a minor code cleanup.
> Add CHANGELOG entry for #345

- .github/workflows/test.yml
This PR updates to latest checkout action version
> Update latest checkout action version
