- lib/rdoc/generator/template/sdoc/resources/css/panel.css
- lib/rdoc/generator/template/sdoc/resources/js/searchdoc.js
Unfortunately I broke the search results behaviour when I [replaced the `h1` with `a` elements in the sidebar](https://github.com/zzak/sdoc/pull/91). ([Bug report](https://github.com/krautcomputing/rubydocs/issues/7))
This should fix it.
> fix styling and behaviour of search results

- .travis.yml
- sdoc.gemspec
it is same reason as https://github.com/rdoc/rdoc/pull/412
And also needs bump version rdoc 5.0, I think.
> Removed needless json dependency and drop to support Ruby 1.8

- sdoc.gemspec
I don't want to install rdoc 5 beta2 to my newly installed ruby 2.4.
> Depend on released version of RDoc 5

- .travis.yml
- spec/spec_helper.rb
Hi,
That's just a tiny pull request that removes some useless requires ; one for 1.8.7 compatibility which is no longer necessary as of https://github.com/zzak/sdoc/commit/c28efc8d4ebe0a50ed1072f3e4041657b149b634. Also, requiring `rdoc/test_case` seems useless since all tests pass.
Have a nice day !
> Remove some useless requires

- lib/rdoc/generator/template/merge/index.rhtml
- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
- lib/rdoc/generator/template/rails/resources/panel/index.html
- lib/rdoc/generator/template/sdoc/resources/panel/index.html
Hi,
That's just a tiny pull request that uses HTML 5 inside the templates. The main audience of an API site is developers so we can safely assume that the users will have a recent browser.
Fixes #100.
Have a nice day !
> Use HTML 5 for templates

- lib/rdoc/generator/template/rails/resources/js/searchdoc.js
- lib/rdoc/generator/template/sdoc/resources/js/searchdoc.js
Hello,
This pull request strips out HTML tags from search results description. This will display search results without any HTML code since, at the moment, all results start with an escaped `<p>` tag.
This is how it looks at the moment on the Rails API:
And how it looks with this patch:
Also, here's [a tiny benchmark](https://gist.github.com/robin850/140ddf33cb55fccf5871500299cad301) showing that `stripHTML` is faster than `escapeHTML` by the way.
Have a nice day !
> Strip out HTML tags from search results description

- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
- I've found a bug on RoR [apidoc](http://edgeapi.rubyonrails.org/classes/ActiveSupport/Cache/MemCacheStore.html) which is generated by sdoc.
- It seems that current regex in strip_tags method is not enough to strip html tags.
```html
<meta name="description" content="A cache store implementation which stores data in Memcached: <a href="https://memcached.org">memcached.org  This is currently the most popular cache store for production websites.">
<meta property="og:description" content="A cache store implementation which stores data in Memcached: <a href="https://memcached.org">memcached.org  This is currently the most popular cache store for production websites.">
```
```html
<meta name="description" content="A cache store implementation which stores data in Memcached: memcached.org …
```
> Fix helper method `strip_tags`

- lib/rdoc/generator/template/rails/_context.rhtml
- lib/rdoc/generator/template/sdoc/_context.rhtml
We can't put line comments before the closing ERB tag. For example, an
ERB input:
Before
<% if true %>
<% end # Comment %>
After
will be compiled into:
#coding:UTF-8
_erbout = String.new; _erbout.concat "Before\n"
; _erbout.concat "  ";  if true ; _erbout.concat "\n"
; _erbout.concat "  ";  end # Comment ; _erbout.concat "\n"
; _erbout.concat "After\n"
; _erbout.force_encoding(__ENCODING__)
This happens to be syntactically valid as Ruby, but a newline character
after the end keyword is eaten unexpectedly.
> Remove problematic line comments in ERB templates

- README.md
The rdoc/rdoc repo is archived this is the correct link.
> Fixes broken upstream issue link in readme.

- .travis.yml
- bin/sdoc
- bin/sdoc-merge
* -KU options is already deprecated from 1.9
* Use latest rubies on travis ci
> Remove -KU option from bin

- lib/rdoc/generator/template/rails/resources/css/panel.css
This should fix an issue with the panel header under Chrome (at least on macOS).
I've tested this change in the inspector, but not "for reals", but I'm pretty sure it will work 🤞.
The need for this fix would probably be obsoleted by #137, but this is a much smaller change
cc @eileencodes @smashwilson who both spotted the issue
> Fix panel header overflow issue in Chrome

- lib/sdoc/templatable.rb
This PR suppresses the following warnings when using Ruby 2.6.0-dev.
```console
% ruby -v
ruby 2.6.0dev (2018-05-08 trunk 63359) [x86_64-darwin17]
% RUBYOPT='-w' sdoc
(snip)
Generating SDoc format into /Users/koic/src/github.com/zzak/sdoc/doc...
/Users/koic/.rbenv/versions/2.6.0-dev/lib/ruby/gems/2.6.0/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:9:
warning: Passing safe_level with the 2nd argument of ERB.new is
deprecated. Do not use it, and specify other arguments as keyword arguments.
/Users/koic/.rbenv/versions/2.6.0-dev/lib/ruby/gems/2.6.0/gems/sdoc-1.0.0/lib/sdoc/templatable.rb:9:
warning: Passing trim_mode with the 3rd argument of ERB.new is
deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
```
The interface of `ERB.new` will change from Ruby 2.6.
> Add …
> Deprecate safe_level of ERB.new in Ruby 2.6

- lib/rdoc/generator/template/rails/class.rhtml
If a class has a method_list, add these to the existing keywords metatag instead of creating a new metatag.
> Use 1 metatag for keywords

- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
For SEO purposes a page should only have 1 h1 header.
In the banner we can use h2 instead.
> Use h2 instead of h1 for banner header

- lib/rdoc/generator/template/rails/resources/css/panel.css
- lib/rdoc/generator/template/rails/resources/i/arrow-down-current.svg
- lib/rdoc/generator/template/rails/resources/i/arrow-right-current.svg
If an item was selected in the panel, the arrow icon was pointing in the
wrong direction.
This uses the correct direction of the arrow.
We also add a new white icon for the selected item for improved
legibility.
> Fix arrow icons for selected panel items

- README.md
- config.ru
- sdoc.gemspec
After switching to Turbolinks all asset paths are absolute.
This breaks opening the files locally in the browser.
To help testing locally add a rack application to serve the
documentation locally.
This is somewhat similar to  #136 but uses Rack::Static instead
to avoid security issues mentioned.
> Add rack application config for testing locally

- lib/rdoc/generator/template/rails/index.rhtml
In the migration to a css based layout the title of the index page got
changed. This reverts the title change back to the @options.title.
> Use @options title for the index

- lib/rdoc/generator/template/rails/resources/css/panel.css
Use `overflow-y: auto` for both tree and result divs.
Using an `orverflow-y: scroll` results in some browsers always displaying the scroll area even when there's no need of a scroll.
Fixes issue #143
> Fix overflow CSS property of panel elements

- lib/rdoc/generator/template/rails/index.rhtml
- lib/rdoc/generator/template/rails/search_index.rhtml
- lib/rdoc/generator/template/sdoc/class.rhtml
- lib/rdoc/generator/template/sdoc/file.rhtml
- lib/rdoc/generator/template/sdoc/index.rhtml
- lib/rdoc/generator/template/sdoc/resources/panel/index.html
- lib/rdoc/generator/template/sdoc/search_index.rhtml
I ran [Lighthouse](https://web.dev/measure/) over https://api.rubyonrails.org/ & one of the things it warned about was:
> Page lacks the HTML doctype, thus triggering quirks-mode
So I went through & update all the instances of the old HTML doctype to be the same as the HTML5 one :)
I've also deployed the `rake test:rails` site to [Netlify](https://gifted-shirley-590be0.netlify.app/) if you'd like to see the results in action.
> Using HTML5 doctype accross all HTML files

- lib/rdoc/generator/template/rails/_context.rhtml
Using h2 tags for section titles and h3 tags method titles makes
everything more semantic, which improves SEO and accessibility.
Because of the existing css classes are still applied no other changes
have to be made.
> Use semantic headers for better SEO

- lib/rdoc/generator/template/merge/index.rhtml
- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
- lib/rdoc/generator/template/rails/search_index.rhtml
- lib/rdoc/generator/template/sdoc/class.rhtml
- lib/rdoc/generator/template/sdoc/file.rhtml
- lib/rdoc/generator/template/sdoc/index.rhtml
- lib/rdoc/generator/template/sdoc/resources/panel/index.html
- lib/rdoc/generator/template/sdoc/search_index.rhtml
As part of: https://github.com/zzak/sdoc/issues/151
One of the lighthouse recommendation is:
>  Does not have a `<meta name="viewport">` tag with `width` or `initial-scale`
So I added one to all the views :) I used the one which ships with the current `rails new`.
> Adding viewport to views

- lib/rdoc/generator/template/rails/resources/js/searchdoc.js
- lib/rdoc/generator/template/sdoc/resources/js/searchdoc.js
I noticed that it's not possible to copy stuff with Ctrl+C on https://api.rubyonrails.org.
I investigated why that is, and found that `searchdoc.js` overrides it as a navigation shortcut.
In my opinion, copying is more important, and there are two other shortcuts (arrow up and Ctrl+I) for navigating up, so this PR just disables the Ctrl+C navigation shortcut.
> Fix Ctrl+C copying

- lib/rdoc/generator/template/rails/resources/js/searchdoc.js
- lib/rdoc/generator/template/sdoc/resources/js/searchdoc.js
TAB is overriden to load the highlighted item in the panel.
This is not recommended for those who rely on screen readers, keyboard
navigation, are visually impaired, or use other tools expecting (some
form) of WCAG compliance.
Partly fixes #158
> Remove TAB override in panel

- lib/rdoc/generator/template/rails/resources/css/reset.css
- lib/rdoc/generator/template/sdoc/resources/css/reset.css
Currently the outline of most elements is reset to 0.
This prevents those that use keyboard navigation to see which item is
currently selected with TAB.
Partly fixes #158
> Remove outline from reset stylesheet

- netlify.toml
Context https://github.com/zzak/sdoc/issues/162
We could totally use Netlify to preview changes we're making to the docs, this could make reviewing PRs way easier.
This is the configuration file we use to tell Netlify how to build our preview, along with some sensible default headers.
We'd need @zzak to connect this Repository to Netlify to enable auto building when a PR is made. We should be able to use the free tier for our needs also :D - I'm happy to jump on a Zoom call or something to help guide through this process.
> Adding netlify.toml - We can use it for PR previews

- spec/helpers_spec.rb
- spec/rdoc_generator_spec.rb
I was getting
```
DEPRECATED: global use of wont_match from ./sdoc/spec/rdoc_generator_spec.rb:37. Use _(obj).wont_match instead. This will fail in Minitest 6.
```
> Fix deprecations in tests

- Rakefile
Options updated for generated test rails documentation. With them, it's faster, and more looks like real life API.
```
Files:       3438
Classes:     4005 ( 3612 undocumented)
Modules:      863 (  651 undocumented)
Constants:    887 (  834 undocumented)
Attributes:   891 (  836 undocumented)
Methods:    23299 (20050 undocumented)
Total:      29945 (25983 undocumented)
13.23% documented
Elapsed: 155.0s
```
```
Files:      1527
Classes:     570 ( 243 undocumented)
Modules:     510 ( 327 undocumented)
Constants:   407 ( 367 undocumented)
Attributes:  455 ( 412 undocumented)
Methods:    4713 (1883 undocumented)
Total:      6655 (3232 undocumented)
51.44% documented
Elapsed: 42.6s
```
> Generate testing rails docs without test classes

- .gitignore
- README.md
- Rakefile
- config.ru
- netlify.toml
I'm trying to fix merge script (https://github.com/zzak/sdoc/issues/152). For that I decided to add script to generate ruby documentation.
To be able run both rails/ruby docs, I changed rack config a bit.
Generated ruby docs look like
and some stats
```
Files:        809
Classes:      993 ( 285 undocumented)
Modules:      195 (  47 undocumented)
Constants:   1194 ( 464 undocumented)
Attributes:   983 ( 244 undocumented)
Methods:     8817 (1401 undocumented)
Total:      12182 (2441 undocumented)
79.96% documented
Elapsed: 46.4s
```
> Add test rake task to generate ruby documentation.

- lib/rdoc/generator/template/rails/resources/css/main.css
This commit fixes h1 and h2 headings which include links, in the Rails documentation.
These are some of the pages affected:
* https://edgeapi.rubyonrails.org/classes/ActiveSupport/StringInquirer.html
* https://edgeapi.rubyonrails.org/classes/ActionController/Base.html
* https://edgeapi.rubyonrails.org/classes/Rails/Railtie.html
> Remove redundant CSS rule breaking link hover visuals in headings

- lib/rdoc/generator/template/rails/_head.rhtml
- lib/rdoc/generator/template/rails/_panel.rhtml
- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/rdoc/generator/template/rails/resources/js/main.js
- lib/rdoc/generator/template/rails/resources/js/searchdoc.js
- lib/rdoc/generator/template/sdoc/class.rhtml
- lib/rdoc/generator/template/sdoc/file.rhtml
Issue https://github.com/zzak/sdoc/issues/158
> Further wins: Add skip navigation link
This adds a link to the top of each of the pages with "Skip to content" as the text which is activated by tabbing through the site, when clicks it, it should take the user to the `#content` `<div>`. The CSS is taken from Bootstrap 4.
[Also video on YouTube demoing this](https://youtu.be/RbXg8BLSDpY)
Chrome is the easiest to verify with, open the preview app & press "tab", a link saying "skip to content" . When you press "return" it should just the focus (and tab index) to the content.
Press `/` to quickly start searching, this is similar to before where we had `CTRL + S` but is more inline with other big sites approaches.
> Adding .sr-only 'skip to content' link

- lib/sdoc/generator.rb
- lib/sdoc/templatable.rb
This PR suppresses "unused variable" warnings.
Note that these variables are actually used by `eval` and `binding`, so this PR just suppresses the warnings but doesn't remove the assignments.
----
By the way, I've got these warnings with IRB. With `RUBYOPT=-w`, they break IRB's completion feature, which is introduced Ruby 3.1-dev. The problem will be fixed by this patch.
before
https://user-images.githubusercontent.com/4361134/132087288-f59cebe5-4e47-48c7-aedb-79ab415d4903.mp4
after
https://user-images.githubusercontent.com/4361134/132087291-5d7cf971-80b6-42ad-8a9d-4a7e7ab2481c.mp4
> Suppress unused variable warnings

- CHANGELOG.md
- lib/rdoc/generator/template/rails/_context.rhtml
- lib/rdoc/generator/template/sdoc/_context.rhtml
Hello,
This pull request simply try to improve the source toggler for ghost methods.
Ghost methods don't have any source associated to their definition so let's avoid displaying a link to show an empty source for them.
We can still point to the definition on GitHub to ease finding the meta-programmed definition as it is most-likely in the same file.
Here's [an example](https://api.rubyonrails.org/v6.1.4/classes/AbstractController/Callbacks/ClassMethods.html#method-i-before_action) of the current behavior with ghost methods.
Have a nice day.
> Avoid displaying source toggler for ghost methods

- sdoc.gemspec
Rdoc 6.4.0 added psych 4.0 as a dependency.
This version of psych is not compatible with ruby 2.5 and lower
resulting in the following error:
ArgumentError: wrong number of arguments (given 4, expected 1)
/home/runner/work/sdoc/sdoc/vendor/bundle/ruby/2.5.0/gems/psych-4.0.3/lib/psych.rb:323:in `safe_load'
As we still support rubies lower that 2.5, we need to add a constraint.
Current Rails master also has rdoc locked to 6.3.3:
https://github.com/rails/rails/blob/7ad7550601a19d94a4bb41b8c49e3bbc3c12b150/Gemfile.lock#L406
Also see: https://github.com/ruby/psych/issues/531#issuecomment-1003310234
> Don't use rdoc 6.4.0 for now

- Gemfile
`psych` version 4 is not compatible with ruby 2.5 and lower
resulting in the following error on CI:
ArgumentError: wrong number of arguments (given 4, expected 1)
/home/runner/work/sdoc/sdoc/vendor/bundle/ruby/2.5.0/gems/psych-4.0.3/lib/psych.rb:323:in `safe_load'
As we don't want to constrain psych in dependent application, the
contraint is added to the Gemfile instead of the gemspec.
> Constrain psych version in Gemfile

- .github/workflows/test.yml
- Gemfile
- sdoc.gemspec
The current cache contains psych 4.0.3 which doesn't work for ruby 2.5.
The Gemfile has a conditional for the the psych version but this fails
because `bundle install` still fails because of the existence of psych
4.0.3
Adding the cache_version clears the corrupted cache.
> Bump bundler cache version on CI

- lib/rdoc/generator/template/rails/_head.rhtml
- lib/rdoc/generator/template/rails/resources/js/main.js
- lib/rdoc/generator/template/rails/resources/js/searchdoc.js
With the migration to a frameless layout, the URLs to assets were made
absolute instead of relative because of Turbolinks asset tracking.
But absolute URLs fail when we have multiple versions of the docs in
subdirectories like: https://api.rubyonrails.org/v6.1/
See: https://github.com/rails/rails/issues/44042
Turbolinks tracking requires absolute URLs
-------------------------------------------
Turbolinks does not consider relative URLs to assets identical when
tracking assets for reload, even if the absolute URL would be the same.
For example when visiting /index.html, in the following css link:
<link rel="stylesheet" href="css/panel.css" type="text/css" data-turbolinks-track="reload" />
... the panel.css would not be seen as identical as when visiting
/classes/Array.html with the …
> Make sidepanel work with relative paths/URLs

- lib/rdoc/generator/template/rails/resources/js/searchdoc.js
When using keyboard shortcuts in the side panel the following error gets
thrown:
Uncaught TypeError: $.browser is undefined
startMoveTimeout https://api.rubyonrails.org/js/searchdoc.js:94
onkeydown https://api.rubyonrails.org/js/searchdoc.js:57
initNavigation https://api.rubyonrails.org/js/searchdoc.js:10
...
$.browser was deprecated in jQuery 1.3 and removed in 1.9; sdoc/rails
currently bundles jQuery 3.5.1. as noted by @dmke.
This browser detection is very old and no longer seems necessary in
modern browsers.
Fixes #173
> Remove unsupported browser detection

- lib/rdoc/generator/template/rails/resources/js/searchdoc.js
When opening the docs locally the side panel doesn't work because visits
with Turbolinks result in errors like:
Uncaught DOMException: Failed to execute 'pushState' on 'History': A
history state object with URL
'file:///sdoc/doc/public/activerecord/README_rdoc.html'
cannot be created in a document with origin 'null' and URL
'file:///sdoc/doc/public/index.html'§
We can detect the protocol of the window and fallback to window.location to
open the URL. This will result in a full page load that will
lose state in the side panel, but it's better than navigation not
working.
> Use window.location instead of Turbolinks.visit if protocol is 'file:'

- .github/workflows/test.yml
- sdoc.gemspec
If the CI runs with older versions of ruby, there is no reason to pin
the rdoc version.
This also changes the github actions tests to run on PRs.
> Add support for rdoc 6.4.0

- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/rdoc/generator/template/rails/resources/css/panel.css
Currently the Rails API documentation inserts a HTML fragment containing
an image to add the Edge badge:
https://github.com/rails/rails-docs-server/blob/c8ca05fc9e434618a8e74b805c5b3fb94cf83caa/lib/generators/main.rb#L29-L45
Instead we can reuse the CSS-based Guides badge.
This also allows us to add the badge for stable versions, just like we
do for the guides.
The badge will only be shown when passing in the HORO_BADGE_VERSION env
variable.
> Allow setting CSS based version badge

- .github/workflows/test.yml
Should fix the following error:
Run bundle exec rake
bundler: failed to load command: rake (/home/runner/work/sdoc/sdoc/vendor/bundle/jruby/3.1.0/bin/rake)
Gem::LoadError: You have already activated jar-dependencies 0.4.1, but your Gemfile requires jar-dependencies 0.4.2. Since jar-dependencies is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports jar-dependencies as a default gem.
Fix is similar to:
https://github.com/sparklemotion/nokogiri/pull/2618
> Use latest Bundler to fix jruby build

- lib/sdoc/generator.rb
It seems like it is okay if `main_page` is nil, see line 209. Given that, I just made line 197 not crash if it is nil.
> `index_path` should handle a nil `main_page`

- lib/rdoc/generator/template/rails/resources/css/github.css
Constants and keymethods have their own css class, but these are currently missing in the css.
> Add css class for constant and keymethods

- lib/rdoc/generator/template/rails/resources/css/main.css
Make code examples a bit more friendly looking by rounding the borders and adding some padding.
This also uses #191
> Add padding and rounded borders to code examples

- lib/sdoc/github.rb
- lib/sdoc/merge.rb
Encountered NoMethodError rather surprisingly during my attempt to run rdoc task for rails/rails with 3.2.0.
Turns out `File.exists?` has been removed as of Ruby 3.2.0: https://github.com/ruby/ruby/commit/bf97415c02b11a8949f715431aca9eeb6311add2
Hence runnig sdoc with 3.2.0 inevitably fails. Let's start to use `File.exist?` instead, shall we?
> `File.exists?` has been removed as of Ruby 3.2.0

- lib/rdoc/generator/template/rails/resources/css/main.css
The behavior of this is weird, as far as I can tell it only justifies paragraphs which have other content, like code or links within them. otherwise it's perfectly fine leaving a paragraph to the current length. Compare these two sentences above.
There are many places in the Rails API docs that are affected by this, so I think it's just easier to remove the CSS rule here.
> Don't justify paragraphs

- Gemfile
- Rakefile
- lib/sdoc/generator.rb
- netlify.toml
This allows us to test building rails documentation and produce the same result that is effectively on `api.rubyonrails.org`.
We can then have a better impression of what changes to sdoc will look like!
> Generate rails using rails

- lib/rdoc/generator/template/rails/_context.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
Currently every method heading includes the text "Link" for the permalink of the method. By removing this outside of the heading we should improve the SEO for these methods.
An alternative could be to make the method itself the permalink.
> Move permalink out of method heading

- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
For top-level modules, like ActiveRecord the huge list of included files is very obtrusive. By moving the files to the bottom more important content is shown first.
To get the footer to stick to the bottom on empty/sparse pages, css-grid is introduced.
> Move file links to the footer

- lib/rdoc/generator/template/rails/resources/css/main.css
Instead of setting a margin of 300px on the `banner`, `#bodyContent` and `footer` we should make use of css grid introduced in: 617ffe2c817f0b5929b27ae09734d98abb187403
Setting the min-width to 0 is required to avoid grid overflow caused by `pre` code blocks.
> Use a proper css grid

- lib/rdoc/generator/template/rails/resources/css/main.css
This allows for more content to fit.
> Use smaller margins on mobile

- lib/rdoc/generator/template/rails/_context.rhtml
Collapse the namespace list by default as it can be very large.
> Collapse namespace section by default

- CHANGELOG.md
- lib/sdoc.rb
- lib/sdoc/name_list.rb
This generator is intended to be used for building two files, based on the work that was done with `JsonIndex`:
* `classes`: the canonical list of public namespaces built from RDoc
* `methods`: a list of all public instance and class methods for a project
> Add NameList

- lib/rdoc/generator/template/rails/_context.rhtml
Alternative implementation to "Make namespace section expandable" 809e71444dbf47af1ebaddf9df0cb39cb304a53a.
Pages that only show namespaces would benefit from having the namespaces expanded. To prevent the namespaces from taking up valuable page real estate we can move the namespaces to the bottom.
This also renames "Namespace" to "Classes and Modules" to better describe the contents of the section.
> Move Namespace section to the bottom and rename to Classes and Modules

- lib/rdoc/generator/template/rails/_panel.rhtml
- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
This makes sure the logo works when generating the docs locally. It also makes sure the logo still works for older rails versions where the version is in the URL, like: https://api.rubyonrails.org/v6.1/
> Make path to logo relative

- config.ru
Ruby 3.2 removed `Dir.exists?` in favor of `Dir.exist?`.
> Fix `config.ru` for Ruby 3.2

- lib/rdoc/discover.rb
This fixes the following warning when running `rake test`:
```
sdoc/lib/rdoc/discover.rb:4: warning: sdoc/lib/rdoc/discover.rb:4: warning: loading in progress, circular require considered harmful - sdoc/lib/sdoc.rb
from ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in  `<main>'
from ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in  `select'
from ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in  `block in <main>'
from <internal:ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in  `require'
from <internal:ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in  `require'
from sdoc/spec/helpers_spec.rb:1:in  `<top (required)>'
from <internal:ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in  `require'
from …
```
> Fix circular loading warning

- Gemfile
- lib/sdoc/templatable.rb
- sdoc.gemspec
This matches `.github/workflows/test.yml` which only tests Ruby >= 2.7.
> Require Ruby >= 2.7

- lib/rdoc/generator/template/rails/resources/js/.gitattributes
The `binary` attribute suppresses each file's contents from the output of `git grep` and `git diff`.  It also excludes each file from the project's language stats on GitHub.
> Mark vendored JavaScript assets as binary in git

- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
- lib/rdoc/generator/template/rails/search_index.rhtml
The `<meta charset>` tag should appear before any elements that contain text, including the `<title>` element.
> Put `<meta charset>` tag first

- lib/rdoc/generator/template/rails/resources/css/main.css
`overflow-x: scroll` always shows a scrollbar, whereas `overflow-x: auto` shows a scrollbar only when necessary.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/7d3d479c-0454-46bf-9052-75535e8be916) | ![after](https://github.com/rails/sdoc/assets/771968/aee894b9-e5b0-4c9a-a4a8-e4ef68d1fd61) |
> Hide scrollbar for unscrollable code snippets

- lib/sdoc/templatable.rb
This hack dates back to 337c94b5761910ed0f51a435fd78a9abf4559467, made in 2009, which corresponds to RDoc v2.4.3.
Since then, the original problem appears to be fixed in RDoc, as can be observed for the `ActionView::Helpers::JavaScriptHelper#javascript_tag` doc in Rails v7.0.6.
> Remove obsolete HTML escaping hack

- lib/rdoc/generator/template/rails/_context.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/sdoc/postprocessor.rb
- spec/postprocessor_spec.rb
Prior to this commit, method source code was syntax highlighted by RDoc and had its own CSS styles.
This commit applies Rouge syntax highlighting to method source code for consistency with other Ruby code blocks, allowing us to reuse the Rouge CSS styles.
> Use Rouge to highlight method source code

- lib/rdoc/generator/template/rails/resources/css/main.css
When method source code is shown and contains long lines, it can overflow and cause the entire page to be horizontally scrollable.
To prevent that, this commit sets `overflow-x: auto` for method source code blocks (the same as for other code blocks), so that only the block is horizontally scrollable.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/8337923f-e61b-426f-a639-89eae78c1cad) | ![after](https://github.com/rails/sdoc/assets/771968/ad2155e8-c2be-45b5-b45f-d05432bdf445) |
> Enable horizontal scrollbar for method source code

- netlify.toml
Netlify's post-processing asset optimization can mask URL issues (for example, see #241), and there is no real benefit to optimizing temporary doc previews.
Additionally, the asset optimization feature is deprecated, and will be sunset on 2023-10-17.  See the [notice in the Netlify build logs](https://app.netlify.com/sites/sdoc/deploys/64bb05af56d7e6000866307f#L1406):
> DEPRECATION NOTICE: Your site has asset optimization enabled. This
> feature will be at end of service on October 17, 2023.
>
> After that date, your builds will continue to work but we won't minify
> or bundle the CSS and JS, and we won't optimize images.
> To remove this warning, remove the processing settings from the
> netlify.toml file.
>
> For more details, read our forum announcement:
> …
> Disable Netlify post-processing asset optimization

- lib/rdoc/generator/template/rails/_context.rhtml
- lib/rdoc/generator/template/rails/_head.rhtml
- lib/rdoc/generator/template/rails/_panel.rhtml
- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
- lib/rdoc/generator/template/rails/resources/js/searchdoc.js
- lib/sdoc/generator.rb
- lib/sdoc/helpers.rb
- lib/sdoc/postprocessor.rb
- spec/helpers_spec.rb
- spec/postprocessor_spec.rb
- spec/spec_helper.rb
The Rails logo in the `data-turbo-permanent` part of the navigation panel uses a path that is static after the first page load.  #228 made the path relative, but it is still static.  This means that, when navigating to a different page, the relative path is re-resolved using that page's URL.
For example, when first visiting `foo/bar.html`, the image URL will be `../i/logo.svg` which resolves to `/i/logo.svg`.  Then, after clicking a link to `foo/bar/qux.html`, the image URL will still be `../i/logo.svg` but will resolve to `foo/i/logo.svg`, causing the image to break.
More generally, any relative URLs in a `data-turbo-permanent` element will break when navigating to a different directory level.  This hinders us from adding static `<a>` elements to the navigation panel as well. (The …
> Replace `rel_prefix` with `<base>` tag + postprocessing

- lib/rdoc/generator/template/rails/_context.rhtml
- lib/rdoc/generator/template/rails/class.rhtml
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
This commit adds a `link_to` helper, inspired by Rails' `link_to` helper.
The helper HTML-escapes the link text and HTML attribute values. Additionally, the helper will convert an `RDoc::CodeObject` to a URL by calling its `path` method.  So instead of writing something like:
```erb
<a href="/<%= rdoc_class.path %>"><%= h rdoc_class.full_name %></a>
```
We can write:
```erb
<%= link_to rdoc_class.full_name, rdoc_class %>
```
> Add `link_to` helper

- lib/rdoc/generator/template/rails/_head.rhtml
- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
- spec/spec_helper.rb
This commit adds helpers to access the following values:
* `ENV["HORO_PROJECT_NAME"]`
* `ENV["HORO_PROJECT_VERSION"]`
* `ENV["HORO_BADGE_VERSION"]`
* `ENV["HORO_CANONICAL_URL"]`
The helpers HTML-escape the values, so instead of writing something like:
```erb
<%= h ENV["HORO_PROJECT_NAME"] %>
```
We can write:
```erb
<%= project_name %>
```
> Add helpers for `ENV["HORO_*"]` values

- lib/rdoc/generator/template/rails/_context.rhtml
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
This commit replaces the `each_letter_group` helper with a `group_by_first_letter` helper.  The `group_by_first_letter` helper serves the same purpose but its implementation is simpler and its output is more easily testable.
> Replace `each_letter_group` with `group_by_first_letter`

- lib/rdoc/generator/template/rails/_context.rhtml
- lib/sdoc/helpers.rb
- lib/sdoc/helpers/github.rb
- spec/helpers_spec.rb
This commit factors a `method_source_code_and_url` helper out from `_context.rhtml`.  This cleans up the template and allows the underlying logic to be tested.
> Factor out `method_source_code_and_url` helper

- lib/rdoc/generator/template/rails/class.rhtml
`RDoc::ClassModule#superclass` will be `nil` for `BasicObject`.  This commit prevents a dangling `&lt;` in that case.
> Skip rendering parent class when superclass is nil

- lib/rdoc/generator/template/rails/_context.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
This commit moves the method alias listing above the method description, putting it closer to the method name.  Since the aliases now precede the description, they cannot be misinterpreted as part of the description, so there is no need to further indent them.
| --- | --- |
| ![before1](https://github.com/rails/sdoc/assets/771968/93582a27-e22a-4b06-91c9-7dea16b0f3c5) | ![after1](https://github.com/rails/sdoc/assets/771968/81ee0df4-05d4-4761-bc3f-113cce0d0b27) |
| ![before2a](https://github.com/rails/sdoc/assets/771968/939b0588-e2e9-4fa4-b830-68a32cc5e9b3) ![before2b](https://github.com/rails/sdoc/assets/771968/bda2486c-ce02-43f6-aaf0-8fd0f784e47c) | ![after2a](https://github.com/rails/sdoc/assets/771968/5ac6c9d2-4a31-4335-a779-af10acb739f2) …
> Move alias listing closer to method name

- lib/sdoc/postprocessor.rb
- spec/postprocessor_spec.rb
RDoc can be overzealous when autolinking words that look like module names.  For example, autolinking every occurrence of "Rails" or "ERB".
This commit uses postprocessing to unlink autolinked code ref links that appear to be unintentional.  If a link's text is an uppercase letter followed by either all lowercase letters (e.g. "Rails") or all uppercase letters (e.g. "ERB"), then it's assumed the link is unintentional, and the link is replaced with the just its text.
These kinds of modules can still be linked by prepending the module namespace (e.g. "::ERB" or "ActionView::Template::Handlers::ERB"), or by manually linking the text (e.g. "{Rails}[rdoc-ref:Rails]").
| --- | --- |
| ![before1](https://github.com/rails/sdoc/assets/771968/448f92fb-b194-42d0-b22a-e4e89c308de9) …
> Unlink unintentional autolinked code ref links

- spec/helpers_spec.rb
Follow-up to 38e9a37c49079d407d242d5ea65539a0b83452f2.
This fixes the following warning when running `rake test`:
> warning: assigned but unused variable - source_url
> Fix "assigned but unused variable" warning

- Rakefile
- lib/sdoc/generator.rb
- spec/rdoc_generator_spec.rb
This adds `ENV["HORO_PROJECT_NAME"]` and `ENV["HORO_BADGE_VERSION"]` to the default site title.  For example, if `ENV["HORO_PROJECT_NAME"]` is "Ruby on Rails" and `ENV["HORO_BADGE_VERSION"]` is "v7.0.0", then the default site title will be "Ruby on Rails v7.0.0 API documentation".
> Include project name and version in default title

- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
This adds the site title to each page's title.  When using the default site title, this will incorporate `ENV["HORO_PROJECT_NAME"]` and `ENV["HORO_BADGE_VERSION"]` into the page title.  For example,
```html
<title>ActiveRecord::Base</title>
```
will become
```html
<title>ActiveRecord::Base - Ruby on Rails v7.0.0 API documentation</title>
```
The intent is to give search engines more context and to differentiate between versions of the documentation.
> Include site title in page titles

- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
This adds `ENV["HORO_PROJECT_NAME"]` and `ENV["HORO_BADGE_VERSION"]` to the `og:title` meta tag.  The intent is to differentiate titles between different versions of the documentation.
Note that `og:title` is typically an abridged form of the page title. `og:title` values longer than ~60 characters may be truncated.  The string " (Ruby on Rails v7.0.0)" is 23 characters, leaving ~40 characters for the full module name.  Most public modules in the Rails API appear to fall within that limit.  But even for those that don't, the project version and name will be truncated first, leaving `og:title` no worse than before.
> Include project name and version in `og:title`

- lib/rdoc/generator/template/rails/class.rhtml
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
Prior to this commit, the value of the `description` and `og:description` meta tags were generated by taking the first 200 characters of a module's comment and then further truncating until the last "." character (if possible).  That approach causes headlines and non-prose elements to be included in the description.  For example, for `ActionController::Base` which has an "Action Controller Base" headline, the description was:
> Action Controller Base  Action Controllers are the core of a web request in Rails.
And for `ActionController::HttpAuthentication::Basic` which begins with a code example, the description was:
> HTTP Basic authentication  Simple Basic example   class PostsController < ApplicationController http_basic_authenticate_with name: "dhh", password: "secret", except: :index …
> Refine meta description

- lib/rdoc/generator/template/rails/class.rhtml
The `keywords` meta tag is ignored by major search engines.  Furthermore, it is difficult to generate significant, unique (i.e. not spammy) keywords from method names.  Consider the keywords generated for the `ActiveModel::Dirty` module:
> ActiveModel::Dirty class, \*\_previously_changed?, \*\_changed?, \*\_change, \*\_will\_change!, \*\_was, \*\_previous_change, \*\_previously\_was, restore\_\*!, clear\_\*\_change, changes_applied, changed?, changed, attribute_changed?, attribute_was, attribute_previously_changed?, attribute_previously_was, restore_attributes, clear_changes_information, clear_attribute_changes, changed_attributes, changes, previous_changes
The keywords include "\*_changed?", "\*_change", "changed?", "changed", and "changes".  If a search engine _were_ to evaluate these …
> Remove `keywords` meta tag

- lib/rdoc/generator/template/rails/index.rhtml
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
This simplifies the code and also paves the way for generalizing `canonical_url`'s parameter.
> Use `nil` for index context

- lib/rdoc/generator/template/rails/_head.rhtml
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
The [Open Graph spec](https://ogp.me/) requires four meta tags: `og:title`, `og:type`, `og:image`, and `og:url`.  We already include `og:title`, as well as `og:description`, so we may as well include the remaining three.
`og:type` can be one of a few predefined values.  The two values that are most suitable are `article` and `website`.  This commit chooses `article` because the `article` type supports additional optional metadata (for example, `article:modified_time`), whereas the `website` type does not.
This commit uses `/i/logo.svg` for `og:image`.  Note that `og:image` must be an abolute URL, so `/i/logo.svg` is combined with `ENV["HORO_CANONICAL_URL"]`.
Lastly, this commit uses a URL based on `ENV["HORO_CANONICAL_URL"]` for `og:url`.
> Add required Open Graph meta tags

- lib/rdoc/generator/template/rails/_head.rhtml
- lib/sdoc/helpers.rb
- lib/sdoc/helpers/git.rb
- spec/helpers_spec.rb
This commit adds the `article:modified_time` meta tag using the commit time from the most recent commit of the code branch.
This _might_ help search engines prioritize newer doc versions as old doc version are no longer updated.
> Add `article:modified_time` meta tag

- lib/sdoc/postprocessor.rb
- spec/postprocessor_spec.rb
RDoc does not provide syntax to style manual code ref links with `<code></code>`.  Wrapping code ref links in `<tt></tt>` or `++` does not give the desired result.  For example,
```ruby
```
is rendered as
```html
{<code>Rails</code><a href="..."><code>}</code></a>
```
and
```ruby
```
is rendered as
```html
<code>{Rails}[rdoc-ref:Rails]</code>
```
This commit uses postprocessing to style unstyled code ref links that look like code.  If the link text does not contain a space or if it matches `/\S\(/` (e.g. `foo(bar, &block)`), it is assumed to be code, and the text is then wrapped with `<code></code>`.
This complements 4837fea087618a3811f246d466a5af9346802369 in that it allows manual code ref links to single-word modules to be styled as if they were autolinks.
| --- | --- …
> Style unstyled code ref links

- lib/sdoc/helpers.rb
- lib/sdoc/helpers/git.rb
This cleans up the code a bit, and ensures that git-related logic checks `git?`.
> Factor out `git_command`

- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
- lib/sdoc/helpers.rb
- lib/sdoc/helpers/git.rb
- spec/helpers_spec.rb
Prior to this commit, the banner at the top of each page would display the value of `ENV["HORO_PROJECT_VERSION"]`.  For Rails, this would either be a bare number, e.g. "7.0.0" without a "v" prefix, or a commit reference, e.g. `main@1234567`.
In contrast, the value of `ENV["HORO_BADGE_VERSION"]` is intended to be more user friendly.  For Rails, it would be e.g. "v7.0.0" or "edge".
This commit changes the banner to display `ENV["HORO_BADGE_VERSION"]` if it is set, and otherwise fall back to `ENV["HORO_PROJECT_VERSION"]`. However, since it may still be valuable for maintainers to know the exact commit that the documentation was generated from, this commit also adds a tooltip to show the abbreviated SHA1 of the commit when hovering over the version.
| --- | --- |
| …
> Prefer `ENV["HORO_BADGE_VERSION"]` version in banner

- Rakefile
- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
- lib/sdoc/generator.rb
- lib/sdoc/helpers.rb
- lib/sdoc/postprocessor.rb
- spec/helpers_spec.rb
- spec/postprocessor_spec.rb
- spec/rdoc_generator_spec.rb
Since 5042d1ea95190aea2abd7641af2e525359bf6271, the value of `ENV["HORO_BADGE_VERSION"]` is preferred over the value of `ENV["HORO_PROJECT_VERSION"]`.  Therefore, we can consolidate the `project_version` and `badge_version` helpers.
Note that while `ENV["HORO_BADGE_VERSION"]` has the format we desire, `ENV["HORO_PROJECT_VERSION"]` is the more obvious and preferable name. After these changes is released, we can encourage consumers (namely, Rails) to set `ENV["HORO_PROJECT_VERSION"]` with the same value as `ENV["HORO_BADGE_VERSION"]` and then to drop `ENV["HORO_BADGE_VERSION"]` altogether.
> Consolidate `project_version` and `badge_version`

- lib/rdoc/generator/template/rails/_panel.rhtml
From https://www.w3.org/WAI/tutorials/images/tips/:
> Usually, there’s no need to include words like “image”, “icon”, or
> “picture” in the alt text. People who can see will know this already,
> and screen readers announce the presence of an image.
And from https://www.a11yproject.com/posts/alt-text/:
> Make sure the description of the image is useful. For example, if the
> image is of a company's logo, the `alt` should be the company's name.
> The word "logo" is not necessary or useful as part of the alternative
> text.
Additionally, this commit uses `project_name` in the alt text instead of hardcoding "Ruby on Rails".
> Drop "logo" from logo image alt text

- lib/rdoc/generator/template/rails/_panel.rhtml
- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
The version badge element uses `position: fixed`, so there is no need to nest it in the banner element.
> Factor out version badge HTML to `_panel.rhtml`

- lib/rdoc/generator/template/rails/index.rhtml
The banner on the index page contains superfluous and even misleading information.  The project name should be conveyed by the page title and logo, and the project version should be conveyed by the page title and version badge.  Furthermore, the "Last modified" time is the mtime of the file on disk, unrelated to the time of the last commit for the file or even for the branch as a whole.
This commit removes the banner from the index page for a cleaner appearance.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/e192b42e-c63b-4a2b-a2dd-3ccc392c8eb3) | ![after](https://github.com/rails/sdoc/assets/771968/1d252c3d-f2f7-4ae9-a4aa-1e62da5236a6) |
> Remove banner from `index.rhtml`

- lib/rdoc/generator/template/rails/file.rhtml
When seeing "Last modified" time in the context of a version-controlled project, users are likely to think it is the time of the last revision. However, the "Last modified" time is the mtime of the file on disk, unrelated to the time of the last commit for the file or even for the branch as a whole.
Since that information can be misleading and is not particularly useful, this commit removes it.
> Remove misleading "Last modified" time from `file.rhtml`

- lib/rdoc/generator/template/rails/_context.rhtml
- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
When wrapping text, Safari and Chrome do not consider `/` nor `:` as word break characters.  Firefox considers `/` as a word break character but not `:`.  This can lead to horizontal overflow issues with long file paths and module names on mobile.
This commit adds a `full_name` helper to insert word-break opportunities into file paths and module names.  It also revises the `link_to` helper to do the same when given an `RDoc::CodeObject`.  The helpers insert `<wbr>` tags which tell the browser that the text can be wrapped at that point.
| Before | (Before) | After |
| --- | --- | --- |
| ![before1a](https://github.com/rails/sdoc/assets/771968/c0cad66c-06a3-4731-839b-4bc99782de41) | ![before1b](https://github.com/rails/sdoc/assets/771968/59fdf51b-25f8-4d1c-8e3e-638496ca4d2d) | …
> Add break opportunities in long names for mobile

- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/rdoc/generator/template/rails/resources/css/panel.css
These `@media` queries are concerned with displaying a side panel that is explicitly 300px wide.  Therefore, they should be expressed in terms of pixels instead of variable-width units.  Also note that `em` in a `@media` query is based on the default font size of the browser configured by the user, _not_ the font size of `<body>`, which seems to have been the intention with these (40 * 15px == 600px => equal space for panel and content).
> Use pixels for `@media` queries

- lib/rdoc/generator/template/rails/resources/css/main.css
Stickying the "Appears in" `<details>` at the bottom of the page causes the element to jump up when it is expanded, which is unexpected and unusual.  Since the element already hides information by default, there is no need to force it to stay all the way at the bottom of the page. This commit removes the sticky positioning and fixes some inconsistencies in the grid definition.
| --- | --- |
| ![before1](https://github.com/rails/sdoc/assets/771968/3f1279d4-bb5f-4579-802a-561aa2e76633) | ![after1](https://github.com/rails/sdoc/assets/771968/bb00e575-a6ab-4143-8c88-ed6d1d0783e9) |
| ![before2](https://github.com/rails/sdoc/assets/771968/9b2fd79f-3906-466e-98a8-419d7f101174) | ![after2](https://github.com/rails/sdoc/assets/771968/2d195807-b621-4c68-a907-06189da74b53) |
> Unsticky "Appears in" element from bottom of page

- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
The "Appears in" file list is collapsed by default to avoid overwhelming the user with very long file lists.  For example, the `Rails` module appears in 125 files.  However the vast majority of modules appear in only in their own file.  And, out of all 1370 modules, only ~50 appear in 10 or more files:
```console
$ grep -c '[.]rb</a>' doc/public/classes/**/*.html | head
doc/rdoc/classes/AbstractController/ActionNotFound.html:1
doc/rdoc/classes/AbstractController/Base.html:1
doc/rdoc/classes/AbstractController/Caching/ClassMethods.html:1
doc/rdoc/classes/AbstractController/Caching/ConfigMethods.html:1
doc/rdoc/classes/AbstractController/Caching/Fragments/ClassMethods.html:1
doc/rdoc/classes/AbstractController/Caching/Fragments.html:1
doc/rdoc/classes/AbstractController/Caching.html:2 …
```
> Redesign "Appears in" file list

- lib/rdoc/generator/template/rails/resources/css/panel.css
As the menu bar is fixed on mobile and overlaps the content we need to add scroll padding for the anchor links to be visible.
Source: https://stackoverflow.com/a/56467997
> Add scroll padding for anchor links on mobile

- spec/rdoc_generator_markup_spec.rb
This fixes the following deprecation warning when running `rake test`:
> DEPRECATED: Use assert_nil if expecting nil from .../sdoc/spec/rdoc_generator_markup_spec.rb:21. This will fail in Minitest 6.
> Fix Minitest deprecation warning

- lib/rdoc/generator/template/rails/resources/css/main.css
Safari does not support the `::marker` psuedo-element.  It does support a `::-webkit-details-marker` psuedo-element, but that element's `content` cannot be set.  Therefore, to achieve the desired appearance in Safari (as well as other browsers), this commit hides the summary marker and uses `summary::before` to render the `+` and `-` icons.
> Fix file list in Safari

- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/rdoc/generator/template/rails/resources/css/panel.css
- lib/rdoc/generator/template/rails/resources/i/dark/tree_bg.svg
Most dark mode colors are copied from the Rails guides.
> Add initial dark mode support

- lib/rdoc/generator/template/rails/_context.rhtml
- lib/rdoc/generator/template/rails/_panel.rhtml
- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/index.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/rdoc/generator/template/rails/resources/css/panel.css
- lib/rdoc/generator/template/rails/resources/i/close.svg
- lib/rdoc/generator/template/rails/resources/i/menu.svg
- lib/rdoc/generator/template/rails/resources/js/main.js
- lib/rdoc/generator/template/rails/resources/js/searchdoc.js
This commit redesigns the banner that was formerly displayed at the top of each page.  The banner and the logo are now integrated, and they also serve as the mobile menu bar.
The `menu.svg` and `close.svg` files are from [Feather icons][feather] v4.29.0, and are [licensed under the MIT license][license].
[feather]: https://feathericons.com/
[license]: https://github.com/feathericons/feather/blob/v4.29.0/LICENSE
| Before | After | Before (mobile) | After (mobile) |
| --- | --- | --- | --- |
| ![before1a](https://github.com/rails/sdoc/assets/771968/fe07450f-84b5-4659-b912-f5d8a1640be3) | ![after1a](https://github.com/rails/sdoc/assets/771968/b12190d5-1510-436a-94ea-6e4c2adcedc4) | ![before1b](https://github.com/rails/sdoc/assets/771968/026365ba-06b9-41e4-ad8d-32aa762f3d62) | …
> Redesign banner and mobile menu bar

- Rakefile
- lib/sdoc/generator.rb
- spec/rdoc_generator_spec.rb
- spec/spec_helper.rb
Prior to this commit, `RDoc::Generator::SDoc#index` exhibited the following incorrect behaviors:
1. When `--main` was not specified, `index` would choose the alphabetically-first file as the main page, instead of the first file in the list of files.
2. When `--main` was specified but was prefixed with `--root`, and `--root` did not start with "rails/", `index` would choose the alphabetically-first file.  (Such as when `--root` was an absolute path, or a deeply nested relative path, or simply a path for a non-Rails project.)
3. When `--main` was specified but was not in the list of files, `index` would choose the alphabetically-first file.
This commit fixes `RDoc::Generator::SDoc#index` such that it:
1. Chooses the first file in the list of files as the default main page.
2. Handles any …
> Fix choice of main page

- lib/rdoc/generator/template/rails/index.rhtml
- lib/sdoc/generator.rb
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
- spec/rdoc_generator_spec.rb
The main page reuses an already-processed file.  All of the ref links in that file will be rendered relative to its path rather than relative to the root.  For example, ref links in `railties/RDOC_MAIN.md` will be relative to `files/railties/`, so a link to `ActiveRecord::Base` would use `../../ActiveRecord/Base.html` instead of `ActiveRecord/Base.html`.
This commit changes `RDoc::Generator::SDoc#index` to dup the processed file and override its `path` value such that links on the main page use the root-relative path (but links on the file's page will still use the `files/`-relative path).
This change also makes it unnecessary to escape occurrences of "Rails" in the main page because, with the correct `href`, the postprocessor will now recognize them as unintentional ref links.
> Fix ref links in main page

- lib/rdoc/generator/template/rails/class.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
This converts the name displayed at the top of each module's page into breadcrumb links.  Each part of the name now links to the corresponding parent module's page.
Closes #212.
---
__Before__
__After__
> Render breadcrumb links for module's parents

- lib/rdoc/generator/template/rails/resources/css/main.css
Prior to this commit, the `<summary>` element of a more-less list was positioned just below the bottom of the `<details>` element, which caused it overlap with any subsequent padding or margin.
This commit extends the `<details>` element by adding bottom padding, and aligns the bottom of the `<summary>` element with the bottom of the `<details>` element so that the `<summary>` is always contained within the block.
| --- | --- |
| ![before1](https://github.com/rails/sdoc/assets/771968/aa35ab41-9530-4148-bd1e-1073845710ef) | ![after1](https://github.com/rails/sdoc/assets/771968/6c0a7139-e1f3-4ee6-82f3-77e15d433966) |
| ![before2](https://github.com/rails/sdoc/assets/771968/1c84d432-4b52-4297-911f-1908e2ea640a) | ![after2](https://github.com/rails/sdoc/assets/771968/f46c2c5 …
> Contain more-less `<summary>` inside `<details>`

- lib/rdoc/generator/template/rails/resources/css/main.css
List items inside `#content` use `var(--space-sm)` as their top margin because `var(--space)` looks too disjointed for single-paragraph items, especially single-line items.  However, when a list item contains an element that itself has a `var(--space)` top margin, the list item's top margin looks mismatched.
This commit adds a style tweak such that all list items in a list with any multi-paragraph items will use `var(--space)` for their top margin. (More specifically, when any item contains a paragraph plus another block level element, such as another paragraph or a code block.)
Unfortunately, this enhancement does not currently work in Firefox because it relies on the `:has()` selector.  However, it is only a minor enhancement, and Firefox plans to support `:has()` in the near future.
| …
> Increase top margin for long list items

- lib/rdoc/generator/template/rails/resources/css/main.css
This style tweak reduces the padding of code blocks to make the code feel less disconnected from the surrounding prose.  (Note that, effectively, `em` is character height whereas `ch` is character width.)
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/35a30689-ab19-4f03-9a63-8a452cc69fc8) | ![after](https://github.com/rails/sdoc/assets/771968/a3a5d281-738d-42b9-829c-185ba369e081) |
> Reduce padding of code blocks

- lib/rdoc/generator/template/rails/resources/js/searchdoc.js
These shortcuts interfere with the browser's own keyboard shortcuts such as <kbd>Ctrl + Shift + I</kbd> to open the developer console.
> Remove keyboard shortcuts that use meta keys

- lib/rdoc/generator/template/rails/_panel.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
The version badge sometimes hides content, especially on mobile.  Since c17deffa99a415ca43f23a3df61b567aacd237dc, we display a user-friendly version number in the top left corner of the screen at all times.  As such, there isn't a need to also display the same information in the top right corner of the screen.
| Before | After | Before (mobile) | After (mobile) |
| --- | --- | --- | --- |
| <img src="https://github.com/rails/sdoc/assets/771968/5265d605-fe5e-481d-a358-a33f8efec2dd" width="215" alt="before"> | <img src="https://github.com/rails/sdoc/assets/771968/4a897151-2666-4a29-89fa-1302fe22f1bd" width="215" alt="after"> | <img src="https://github.com/rails/sdoc/assets/771968/11a7e32c-4d26-442b-a6d5-5b3ffea7393e" height="120" alt="mbefore"> | <img …
> Remove version badge

- lib/rdoc/generator/template/rails/_head.rhtml
Via [MDN][]:
> If present, [the attribute's] value must be an ASCII case-insensitive match for "utf-8". It's unnecessary to specify the charset attribute, because documents must use UTF-8, and the script element inherits its character encoding from the document.
[MDN]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#deprecated_attributes
> Remove deprecated `charset` attributes

- lib/rdoc/generator/template/rails/_head.rhtml
- lib/rdoc/generator/template/rails/resources/js/@hotwired--turbo.js
Turbo triggers a `turbo:load` event immediately after it is loaded.  If a deferred script (such as a module) adds a listener for `turbo:load`, and Turbo itself is not deferred, then the listener will only be invoked on subsequent visits.
This commit replaces the UMD version of Turbo with the ESM version so that its loading is deferred.
> Use ESM version of Turbo

- lib/sdoc/generator.rb
- spec/rdoc_generator_spec.rb
This commit allows `RDoc::Generator::SDoc#index` to resolve the main page when the `--main` or `--files` options specify unresolved file paths such as `sibling/../actual/file.md`.
> Support unresolved file paths for main page

- lib/sdoc/generator.rb
- lib/sdoc/templatable.rb
- spec/rdoc_generator_spec.rb
The `$dryrun` global variable in `SDoc::Templatable#render_template` is defunct and causes "warning: global variable `$dryrun` not initialized" to be printed when warnings are enabled.
This commit replaces `$dryrun` with `@options.dry_run`.
> Use `@options.dry_run` in `render_template`

- lib/sdoc/helpers/git.rb
- spec/helpers_spec.rb
Prior to this commit, git commands (such as the command to get `remote.origin.url`) would always be run if git was installed.  This caused "fatal: not a git repository" to be printed to `stderr` when the project was not a git repository.
This commit modifies `SDoc::Helpers::Git#git?` such that git commands will only be run if git is installed _and_ the project is a git repository.
> Prevent git commands if project is not a git repo

- lib/sdoc/helpers.rb
- lib/sdoc/search_index.rb
- spec/helpers_spec.rb
The `page_description` helper extracts the description from the leading paragraph of its input.  Prior to this commit, a paragraph following an `<h1>` was recognized as a leading paragraph, but a paragraph following any other heading was not.
This commit changes `page_description` such that it selects the `<p>` that is the first non-heading element of its input.
> Extract page description after any leading headings

- lib/rdoc/generator/template/rails/_head.rhtml
- lib/rdoc/generator/template/rails/class.rhtml
This adds a `<meta name="description">` tag for the main page and for other prose files such as README files.  The tags are generated in the same way as for code files.
> Add description `meta` tag for prose files

- lib/rdoc/generator/template/rails/resources/css/main.css
Prior to this commit, when the `#content` element had horizontal overflow on mobile, the `<body>` element would become horizontally scrollable, and the banner would scroll off screen when scrolling.
This commit adds `overflow-x: auto` to `#content` so that horizontal scrolling is limited to the `#content` element and the banner remains fixed in place when scrolling.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/e08c59eb-af8d-426f-af0e-a226465efb52) | ![after](https://github.com/rails/sdoc/assets/771968/c7dda4c3-c75e-4abc-8086-6cf9b899d645) |
> Horizontally sticky banner on mobile

- lib/rdoc/generator/template/rails/file.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
For prose files, such as `README` files, it is reasonable to assume that the file content includes an `<h1>` heading, and that the file name is mostly irrelevant.  For example, the file `railties/README.rdoc` includes the heading "Railties -- Gluing the Engine to the Rails".
This commit removes the `<h1>` for a prose file's name, and preserves the file's original `<h1>` instead of making it a subheading of an `<hgroup>` as is done for module descriptions.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/5334c5dc-b511-4bf0-b137-3df97751ed7f) | ![after](https://github.com/rails/sdoc/assets/771968/b4d9248b-2708-4114-a86d-3a945b4dc099) |
> Conserve <h1> headings in prose files

- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
This PR includes a handful of commits that improve readability when using dark mode.
Closes #307.
| Before (Firefox defaults) | After (Firefox defaults) | Before (18px serif, 17px mono) | After (18px serif, 17px mono) |
| --- | --- | --- | --- |
| ![before-dark-defaults](https://github.com/rails/sdoc/assets/771968/067b25b5-71ce-44f0-b43c-8c196c14f1ef) | ![after-dark-defaults](https://github.com/rails/sdoc/assets/771968/df9a8f3b-15e1-4365-8648-fcd6a117bfca) | ![before-dark-custom](https://github.com/rails/sdoc/assets/771968/ae355110-0827-4b67-b69f-a7a380e5fb28) | ![after-dark-custom](https://github.com/rails/sdoc/assets/771968/0de242d0-62c8-4ee5-b2dd-6e9aa3eb2829) |
| ![before-light-defaults](https://github.com/rails/sdoc/assets/771968/3a116acc-2186-430e-ac7b-c856b09c7e9a) | …
> Increase text contrast for dark mode

- lib/rdoc/generator/template/rails/resources/css/main.css
This makes it so that `<code>` elements in search results and `<code>` elements in other `.description` blocks have the same style.
> Add padding to `<code>` elements in search results

- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
When declaring a class with a flattened name like `class Foo::Bar` rather than `module Foo; class Bar`, RDoc does not return a parent object for `Bar`.  Note this only applies to classes.  When `Bar` is merely a module, RDoc _does_ return a parent object.
That behavior caused `module_breadcrumbs` to return only the class's name in such cases.  This commit fixes `module_breadcrumbs` to work around that behavior and always return all breadcrumbs.
> Fix breadcrumbs for flattened class declarations

- lib/sdoc/generator.rb
This factors `debug_msg` calls into `render_file`, which displays the file output path.  Each output path indicates what kind of documentation was rendered.  For example, files output to `classes/` contain class documentation.
> Refactor debug messages

- lib/rdoc/generator/template/rails/resources/css/main.css
This allows the `text-decoration` hack for code links to be applied only in browsers that do not support `:has()` (namely, Firefox).
> Use `@supports` for `:has()` feature detection

- lib/sdoc/generator.rb
The code that used this attribute was removed in 73ace3664fe28d9afe2d4533539d707777c0839f.
> Remove `RDoc::Options#search_index`

- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/rdoc/generator/template/rails/resources/js/main.js
a67ece6220f8da3ed7f3319b89550234d1728382 changed the HTML around method permalinks, which broke the spotlight effect when navigating to a specific method.  However, prior to that commit (since upgrading to Turbo v7), the spotlight effect only worked for cross-page navigation, not intra-page navigation.  This commit fixes the spotlight effect for both cross-page and intra-page navigation.
Additionally, this commit changes the visual effect from a momentary flash of yellow to a persistent mark in the left margin.  This ensures that effect is not missed (for example, when opening the page as a background tab), and is less jarring when using dark mode.
| --- | --- |
| ![before-light](https://github.com/rails/sdoc/assets/771968/b1fbffcf-f40f-4790-8f74-cd6d351e8559) | …
> Rework method spotlight effect

- Rakefile
- lib/rdoc/generator/template/rails/resources/js/@hotwired--turbo.js
Follow-up to 5687727c1301e27c82bd6af25746d5f676d69b24.
This updates the `vendor_javascript` Rake task to download the ESM version of the JavaScript package instead of the UMD version.
> Update `vendor_javascript` Rake task to download ESM

- lib/rdoc/generator/template/rails/_panel.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/rdoc/generator/template/rails/resources/i/search.svg
This was originally attempted in 88a61abd1ed1d4d0100d2ef97671719fe0ec9334 but reverted in 68dbaf68efdc876dce2c0cfeb2ec6c3fb1c788c8 due to an extra magnifying glass icon being shown in Webkit-based browsers.
This commits changes the search input to use `type="search"`, and adds the necessary CSS to hide the native magnifying glass icon.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/e630f498-cd24-4b51-8359-449126383c5a) | ![after](https://github.com/rails/sdoc/assets/771968/fa29d815-af23-4e32-b764-f35b3b428b5b) |
> Use `type="search"` for search input

- lib/rdoc/generator/template/rails/_panel.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/rdoc/generator/template/rails/resources/js/main.js
Since d0e2ead20f0ca159503b2871667452abcedd4c2e, the table of contents for a page is now in the sidebar / mobile menu instead of at the top of the page, which eliminates the major use case for a scroll-to-top button.
Furthermore, there are alternative ways to scroll to the top of the page.  On desktop, the user can click the scoll bar or press the <kbd>Home</kbd> key.  On mobile, the UX is less consistent, but still possible.  For example, in iOS, the user can double-tap the status bar, whereas Android has its own gestures.  While a scroll-to-top button could provide a unified UX, due to limited screenspace, it is even more likely to obscure content and be in the way.
Also, it is worth pointing out that one of uBlock Origin's bundled filter lists ("EasyList - Annoyances") [blocks …
> Remove scroll-to-top button

- lib/rdoc/generator/template/rails/resources/css/main.css
This enforces a maximum width of approximately 75 characters so that lines don't become too long on wide screens.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/05ac8b4e-0f6b-4fad-8c1e-8929ae1566f3) | ![after](https://github.com/rails/sdoc/assets/771968/2b0fb80d-20da-4a52-841c-014677ce1a75) |
The trade-off here is that code examples with long lines are more likely to be cut off.
> Set `max-width` for `#content`

- lib/rdoc/generator/template/rails/resources/css/main.css
This adds a tip above the search results with instructions on how to explicitly search for methods.  The tip is hidden (in browsers that support the `:has()` selector) when one of the first three search results is a method.
| --- | --- |
| ![before1](https://github.com/rails/sdoc/assets/771968/0c3efde4-a81a-497e-9e61-68e24a28ac92) | ![after1](https://github.com/rails/sdoc/assets/771968/7dd6acd0-cc70-4db5-b407-b9a2c2ef69a8) |
| ![before-after2](https://github.com/rails/sdoc/assets/771968/1b004f84-4ef2-4cb8-8437-ef4c10c5f784) | ![before-after2](https://github.com/rails/sdoc/assets/771968/1b004f84-4ef2-4cb8-8437-ef4c10c5f784) **(same)** |
> Add tip about explicitly searching for methods

- lib/rdoc/generator/template/rails/resources/css/main.css
This makes it easier to override those styles when using selectors of the same precedence (for example, overriding `.content` styles in `.panel__nav`).
> Move generic styles higher in the stylesheet

- lib/rdoc/generator/template/rails/resources/css/main.css
When search results are rendered, the result cursor is set to the first result and is scrolled into view via `scrollIntoView({block: "nearest"})`. Typically, this call to `scrollIntoView` would be a no-op.  However, 6eb2e4293638034ce078449510867a537aff7f03 added a "TIP" at the top of the results container.  Thus if the results container has `max-height: 0`, the `scrollIntoView` call will set the scroll position below the "TIP". Such is the case when clicking a `.query-button` or using the `?q=` URL param, because the `.active` class is not yet applied to the results container.
This commit modifies the CSS so that the "TIP" is only shown when the `.active` class is applied.  Thus the `scrollIntoView` call will remain a no-op even when the results container has `max-height: 0`.
> Fix search results initial scroll position

- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/rdoc/generator/template/rails/resources/js/main.js
Turbo Drive breaks the browser's back / forward buttons when navigating to a history entry that was not added by Turbo Drive.  (The URL in the address bar changes, but the page itself does not.)  Therefore, this commit abandons working around Turbo Drive to fix `:target` behavior, and adds an explicit `.target` class in response to navigation events instead.
> Use explicit class instead of `:target`

- lib/sdoc/search_index.rb
- spec/search_index_spec.rb
This prevents some unexpected results.  For example, matching `ActionCable::Connection::StreamEventLoop` when searching for "select" due to "S"tream"E"vent"L"oop.
> Exclude downcased acronym bigrams

- lib/rdoc/generator/template/rails/_head.rhtml
This circumvents the `main.js` => `search.js` => `search_index.js` request chain to increase initial page load speed.
> Preload search JavaScript modules

- lib/rdoc/generator/template/rails/resources/js/search.js
- lib/sdoc/search_index.rb
- spec/rdoc_generator_spec.rb
- spec/search_index_spec.rb
Trigrams can provide more accurate search results than bigrams.  For example, using bigrams, searching for "sel" would attempt to match the ngrams " s", "se", and "el".  For the Rails API (at `7c65a4b83b583f4f`), the top result is `ActiveModel::Serializers` due to "Model" matching "el" and ":Serial" matching " s" and "se".  However, using trigrams, "sel" would attempt to match " se" and "sel".  In that case, for the Rails API, the top result is `ActiveRecord::QueryMethods#select`.
The downside to using trigrams is that the search index increases from 2.9 MB to 8.6 MB.  But the data compresses well, so when gzipped the size only increases from 474 kB to 670 kB.  And browser heap snapshot size stays reasonably small, increasing from 6.8 MB to 11.1 MB in Firefox and 8.0 MB to 22.2 MB in …
> Switch from bigrams to trigrams for search

- lib/sdoc/search_index.rb
- spec/search_index_spec.rb
Prior to this commit, modules would rank above methods in search results.  This ensured, for example, that `ActionController::Rendering` would rank above `ActionController::Rendering#render` when searching for "ActionController::Rendering".  However, `ActionController::Rendering` would also rank above `ActionController::Rendering#render` when searching for just "render".  Though the method _does_ rank first when searching for "#render" or ".render", such queries may not be intuitive.
Based on the idea that users will be searching for _either_ a module _or_ a method, this commit removes the higher-ranked module-specific ngrams from method entries in the search index.  For example, the method entry for `ActionController::Rendering#render` will no longer include the ":Ac", " Ac", ":Re", and …
> Adjust module vs method ranking in search results

- lib/sdoc/postprocessor.rb
- spec/postprocessor_spec.rb
Similar to ffcaf8184e5a30a61038010cbde7d8ea5bfaab83, this uses postprocessing to version explicit links to api.rubyonrails.org.  For example, if `ENV["HORO_PROJECT_VERSION"]` is "3.2.1" (and `ENV["HORO_PROJECT_NAME"]` is "Ruby on Rails"), then
```html
<a href="https://api.rubyonrails.org/classes/ActiveRecord/Base.html">Learn more</a>
```
will be changed to
```html
<a href="https://api.rubyonrails.org/v3.2.1/classes/ActiveRecord/Base.html">Learn more</a>
```
This allows such URLs to be used in `README.rdoc` files instead of using `link:classes/ActiveRecord/Base.html`, which is not properly resolved when the link is rendered on e.g. GitHub.
> Version explicit links to `api.rubyonrails.org`

- lib/rdoc/generator/template/rails/resources/css/main.css
This fixes a 1px width difference between `.banner` and `.panel__tray` on desktop due to the additional border on `.panel__tray`.  Mobile is unaffected.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/2124b643-31ac-48ac-9540-d5c9d294ac5c) | ![after](https://github.com/rails/sdoc/assets/771968/9b394b6e-ccbc-4542-959c-cce09f7c64bc) |
> Fix 1px width difference between banner and tray

- lib/rdoc/generator/template/rails/resources/css/main.css
Prior to this commit, code blocks wrapped in `<pre><code>` had `font-size: 0.95em` applied twice, resulting in a font size of 0.9025em (e.g. 18.05px instead of 19px when the body font size is 20px).  This commit fixes such elements to have the intended font size.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/96c2a9f3-dede-4a0b-a552-01a24c49281b) | ![after](https://github.com/rails/sdoc/assets/771968/aa2d72ce-dfcf-4c00-8789-d9d2482ddad7) |
> Fix font size of nested code elements

- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
Follow-up to 65c34da1fbd210158520e00636c1d161581722e4.
This fixes the `method_signature` helper to handle multi-line `:call-seq:` method signatures by wrapping the entire signature in `<code>` (which is styled with `white-space: pre-wrap`).
> Fix multi-line `:call-seq:` method signatures

- lib/sdoc/rdoc_monkey_patches.rb
- spec/rdoc_monkey_patches_spec.rb
RDoc includes extra whitespace in a method's parameter list when the the method's `def` statement is spread across multiple lines.  For example, a `def` like:
```ruby
def define_attribute(
name,
cast_type,
default: NO_DEFAULT_PROVIDED,
user_provided_default: true
)
end
```
Would produce a parameter list like:
```
( name, cast_type, default: NO_DEFAULT_PROVIDED, user_provided_default: true )
```
This commit monkey-patches `RDoc::AnyMethod#params` to remove the extra whitespace within the parentheses:
```
(name, cast_type, default: NO_DEFAULT_PROVIDED, user_provided_default: true)
```
This is implemented as a monkey patch so that it fixes `params` for rendered method docs as well as search index entries.
| --- | --- |
| …
> Remove extra whitespace in method signature params

- lib/sdoc/search_index.rb
- spec/search_index_spec.rb
Prior to this commit, search results displayed `(...)` as the parameter list for any `:call-seq:` method.  The reason being the `:call-seq:` value may contain method overloads (i.e. multiple parameter lists) or even arbitrary text.  However, it is common for the `:call-seq:` value to be basic method signature with a single parameter list.  Therefore, this commit handles that case and otherwise falls back to `(...)`.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/8ae055d3-e619-45e6-8d18-08a735688095) | ![after](https://github.com/rails/sdoc/assets/771968/b1aea571-3f8b-428a-a3f0-3810c0db787c) |
> Extract basic `:call-seq:` params for search results

- lib/sdoc/helpers.rb
`RDoc::Store#find_module_named` does not find classes (though `RDoc::TopLevel#find_module_named` and `RDoc::Context#find_module_named` both do).  Thus, prior to this commit, when a parent module was a class, its breadcrumb would not be linked.
This commit fixes the issue by changing `RDoc::Store#find_module_named` to `RDoc::Store#find_class_or_module`.
> Fix `module_breadcrumbs` when parent is a class

- lib/rdoc/generator/template/rails/_context.rhtml
- lib/rdoc/generator/template/rails/_module_nav.rhtml
- lib/rdoc/generator/template/rails/file.rhtml
- lib/sdoc/helpers.rb
- spec/helpers_spec.rb
`RDoc::CodeObject#comment` appears to always return a string, even if no comment has been specified.  Thus the truthiness of `comment` cannot be used to skip rendering empty descriptions.
This commit adds a `description_for` helper to encapsulate properly checking `comment` and wrapping the rendered description in a `div`.
This commit also renames the `full_name` and `short_name` helpers to `full_name_for` and `short_name_for` to match `description_for`.
> Skip rendering empty descriptions

- CHANGELOG.md
- lib/rdoc/generator/template/rails/_context.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/sdoc/postprocessor.rb
- spec/postprocessor_spec.rb
This changes the appearance of the "Constants" section to match the "Methods" sections.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/a95d8c34-0177-4722-9bf3-7891ae8b59f5) | ![after](https://github.com/rails/sdoc/assets/771968/f4fca647-0fc3-4a3e-8dcc-02f67c5b0356) |
> Redesign "Constants" section

- CHANGELOG.md
- lib/rdoc/generator/template/rails/_context.rhtml
- lib/rdoc/generator/template/rails/_module_nav.rhtml
- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/sdoc/rdoc_monkey_patches.rb
- spec/rdoc_monkey_patches_spec.rb
This adds a permalink next to each constant's name, similar to methods. This also adds a "Constants" navigation section in the sidebar, similar to the "Methods" navigation section.
The permalinks are implemented by monkeypatching `RDoc::Constant` to provide an `aref` method, just as `RDoc::ClassModule` and `RDoc::MethodAttr` already do.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/469dbbb0-17de-4829-a716-85501c3a5e5b) | ![after](https://github.com/rails/sdoc/assets/771968/3c93549a-1793-41f9-9448-cbd82ccb79c7) |
> Support permalinking constants

- CHANGELOG.md
- lib/rdoc/generator/template/rails/resources/css/main.css
- lib/rdoc/generator/template/rails/resources/js/main.js
- lib/sdoc/search_index.rb
- spec/search_index_spec.rb
This makes constants searchable, just like methods.
| --- | --- |
| ![before](https://github.com/rails/sdoc/assets/771968/fb2f1f4d-4321-4ef9-8af8-8db277767eca) | ![after](https://github.com/rails/sdoc/assets/771968/0bf377b9-1fd0-4b0d-aaee-4e05b7aa51ba) |
> Add constants to search index

- lib/sdoc/helpers/git.rb
- spec/helpers_spec.rb
In d08ca4d758f2633b9a2a49a045d56d4856c2e5e4, an isolated scope was created for each rendered file.  That inadvertently reset memoized values from `git` calls for each file, causing a performance regression.
This commit fixes the regression by memoizing the values globally.
With d08ca4d758f2633b9a2a49a045d56d4856c2e5e4~1 (444c4a46211d305353485f21012c3c242104b0e4):
```console
$ time bundle exec rake test:rails
real  0m31.567s
user  0m31.159s
sys 0m0.394s
```
With d08ca4d758f2633b9a2a49a045d56d4856c2e5e4:
```console
$ time bundle exec rake test:rails
real  1m11.195s
user  1m2.671s
sys 0m8.811s
```
With d08ca4d758f2633b9a2a49a045d56d4856c2e5e4 + this commit (retrofitted):
```console
$ time bundle exec rake test:rails
real  0m26.155s
user  0m25.796s
sys 0m0.331s
```
With `main`:
```console
$ …
```
> Fix performance regression due to git calls

- CHANGELOG.md
- README.md
Found via `typos --format brief`
> Fix typos in readme and changelog

- Gemfile
- Rakefile
As Rails 7.1 is released we can remove this monkeypatch.
> Remove Rails 7.1 testing monkeypatch

- CHANGELOG.md
- lib/rdoc/generator/template/rails/_context.rhtml
- lib/sdoc/search_index.rb
- spec/search_index_spec.rb
|--------|--------|
| ![image](https://github.com/user-attachments/assets/5ff31ff1-82b9-4c80-898d-91b072d8b87d) | ![image](https://github.com/user-attachments/assets/d79a31f8-dee2-4138-99dc-c2654113304d) | 
To make this work correctly, add anchors to the generated html.
RDoc uses the same class for methods and attributes so most of the plumbing was already there.
Closes #369. I oriented myself with https://github.com/rails/sdoc/pull/358 which is the PR for adding constants to the search.
> Add attributes to the search index

- Gemfile
- README.md
- config.ru
* Rack::Static is not autoloaded anymore
* Headers must be lowercase (not sure where Rack::Lint is coming from)
I prepend `bundle exec` to commands because I end up activating rack 2.2.9 beforehand otherwise.
This _probably_ still works with rack 2 as well but does it have to? Closes #366
> Make Rack 3 work OOTB

- lib/sdoc/rdoc_monkey_patches.rb
ruby/rdoc@4a5206ae564fb6c3ba78e200b776001785c30839 added a kwarg to `RDoc::Markup::ToHtmlCrossref#cross_reference` which must be forwarded.
This commit adds a double-splat (`**`) to the `cross_reference` monkey patch in order to forward that kwarg.  It also adds a splat (`*`) in case more positional args with default values are added in the future.
> Fix compatibility with RDoc >= 6.10.0

- lib/sdoc/generator.rb
- lib/sdoc/rdoc_monkey_patches.rb
- spec/spec_helper.rb
This PR addresses two issues with RDoc 6.13.0:
* ruby/rdoc@694987be2bc244ceb4686ee75a1272cc9e27313c removed support for `file_dir` and `class_dir`, which we use to prefix URL paths with `files/` or `classes/` (for example, in the URLs for https://api.rubyonrails.org/files/activerecord/lib/active_record/base_rb.html and https://api.rubyonrails.org/classes/ActiveRecord/Base.html).
* ruby/rdoc@f517b028c6e5957fb546aa619559dca3abf05993 changed the signature of `RDoc::Store#initialize` from `initialize(path = nil, type = nil)` to `initialize(options, path: nil, type: nil)`, which is a breaking change.
> Fix compatibility with RDoc 6.13.0

- lib/sdoc/generator.rb
- lib/sdoc/rdoc_monkey_patches.rb
- spec/helpers_spec.rb
- spec/spec_helper.rb
Follow-up to #375.
RDoc 6.13.1 has been released, and includes support for the `class_module_path_prefix` and `file_path_prefix` options (added in ruby/rdoc@3bc179ddfb74b46c52f697b9d1ce331264fcd84c), which serve as replacements for the `class_dir` and `file_dir` methods.
This commit removes the RDoc monkey patch added in e2d849f48cb2ed3effe39a674ca79de7e8fb812b in favor of using those options.  This means SDoc will be incompatible with RDoc 6.13.0 specifically, but that shouldn't be a significant issue (and compatibility with RDoc < 6.13.0 is preserved).
> Use `{class_module,file}_path_prefix` RDoc options
